academy_join:
    resource: "@AcademyJoinBundle/Resources/config/routing.yml"
    prefix:   /

join:
    pattern: /join/
    defaults: { _controller: TrainingJoinBundle:Default:index}
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
